### PR TITLE
W1-api for attractions

### PR DESCRIPTION
**Pull request by kristychaotw**
Hi PengPeng,
please review my code, thank you!
I'm Kristychao (趙孔嘉)

### 1. api/attractions
http://54.161.96.147:3000/api/attractions?path=1&keyword=公園
### 2. api/attraction/{id}
http://54.161.96.147:3000/api/attraction/3

### CODE REVIEW

**Comment by cwpeng** [comment]
1. "nextPage" of http://54.161.96.147:3000/api/attractions?page=0&keyword=%E5%85%AC%E5%9C%92 and http://54.161.96.147:3000/api/attractions?page=4 should be null, because they have reached the final page of results.

Fix issue and leave comment for me to review again.

**Comment by kristychaotw** [comment]
Hi  PengPeng, @cwpeng 
I fixed the problems. Please take a look at the work. Thanks!

**Comment by cwpeng** [comment]
I just connect twice. Server is broken. Find the cause and fix it.

**Comment by kristychaotw** [comment]
I reactivate it. Is it working now? @cwpeng

**Review by cwpeng — COMMENTED** [review]
We should assume attractions data may be changed during the lifetime of website. So, code below, which only works under certain number of data, is not acceptable.
```
			if p < 4:
				return {"nextPage": dataP[0],"data":dataP[1]}
			elif p==4:
				return {"nextPage": None,"data":dataP[1]}		
			else:
				return "error: 此頁數無資料"
```

Your paging strategy in keyword searching is OK. Use it again here.

**Comment by kristychaotw** [comment]
Hi PengPeng, @cwpeng 
I adjusted the code in API. Please take a look. Thank you.

**Comment by cwpeng** [comment]
Re-request me review from right side in this page.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by kristychaotw** [comment]
Thank you!

**Pull request merged**
