### PR TITLE
W4-Member System

### PR DESCRIPTION
**Pull request by kristychaotw**
Hi PengPeng, @cwpeng 
I'm Kristy (趙孔嘉).
Please review my week4 assignment. Thank you.

### Testing links:
http://54.161.96.147:3000/
http://54.161.96.147:3000/attraction/2

### CODE REVIEW

**Comment by cwpeng** [comment]
I cannot connect to your server for now.

**Comment by kristychaotw** [comment]
@cwpeng 
I reactivated the connection and it should be working now. 
please have a look.

**Comment by cwpeng** [comment]
Your API response 500 error after some simple testing. Try to check logs in server, find root cause and fix it.

**Comment by kristychaotw** [comment]
Hi PengPeng, @cwpeng 
I added a connection pool in my app and also adjust some of my sqlquerys.
The website should be working now.
Please take a look at it. Thank you.

**Review by cwpeng — APPROVED** [review]
Finally, you made it. Task Done.

**Comment by kristychaotw** [comment]
Finally!!!!Thank you Pengpeng.

**Pull request merged**
