### PR TITLE
W2-ver1 review

### PR DESCRIPTION
**Pull request by kristychaotw**
Here is my website:
http://54.161.96.147:3000/

## Update
1. infinite scrolling
2. keyword searching

Please review my work, thank you.

### CODE REVIEW

**Comment by kristychaotw** [comment]
Hello Pengpeng, @cwpeng 
I'm Kristy Chao (趙孔嘉).
Please review my work, thank you.

**Comment by cwpeng** [comment]
Your code will load the same page data many times when we scroll down to bottom. And attraction info text and list layout are broken, too.

未命名-2

**Comment by cwpeng** [comment]
You can try to use a global variable to track API loading status. Set it to true before start of calling API, set to false after end. Use it to make sure our code only loads API once at the same time.

**Comment by kristychaotw** [comment]
Hi Pengpeng, @cwpeng 
Sorry for that bug.
I didn't encounter that issue when I first tested it.
To solve it,  I added a variable as a switch to handle the multiple requests.
I made a test again and I think the bug is solved now. 
However, I am not sure if my method is the same as what you suggest......
can I use this method and is it a good method?

**Review by cwpeng — APPROVED** [review]
OK. Well Done.

What you do is good. Just test carefully, and take more confidence to yourself.

**Comment by kristychaotw** [comment]
Thank you so much!
Stage 2 is a process of destroying confidence lol
Hope I can build it back and build it much more stronger.

**Comment by cwpeng** [comment]
you will. :)

**Pull request merged**
