### PR TITLE
W3-attraction page

### PR DESCRIPTION
**Pull request by kristychaotw**
Hello Pengpeng,
I'm Kristy (趙孔嘉)
Please review my work, thank you! 

### Webpages for testing
http://54.161.96.147:3000/
http://54.161.96.147:3000/attraction/11

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Slider should close to left and right border of screen in mobile layout.
2. Slider will be broken if we click next many times.

未命名-7

**Comment by kristychaotw** [comment]
Hi Pengpeng @cwpeng ,
I fixed the slider's border and size.
Please review it again. Thanks!

**Comment by kristychaotw** [comment]
Hi Pengpeng @cwpeng ,
I fixed the sliders' border and size.
Please review it again. Thank you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
